version: "3.8"

services:
  db:
    image: postgres:8.3
    environment:
      POSTGRES_DB: minimundo
      POSTGRES_USER: minimundo
      POSTGRES_PASSWORD: minimundo
    ports:
      - "5432:5432"

  app:
    image: jboss/wildfly:7.0.2.Final
    ports:
      - "8080:8080"
    depends_on:
      - db
